services:
  hazelcast-server:
    build:
      context: ./Indexer
    container_name: hazelcast-server-${NODE_ID}
    networks:
      - hazelcast-network
    ports:
      - "5040:5040"
    environment:
      - NODE_ID=${NODE_ID}
      - HAZELCAST_CONFIG=/app/resources/indexer_server_hazelcast.xml
    volumes:
      - ./Indexer/resources:/app/resources

  hazelcast-client:
    build:
      context: ./Crawler
    container_name: hazelcast-client
    networks:
      - hazelcast-network
    volumes:
      - "C:/pub/tmp/datalake:/app/mounted-folder"
      - ./Crawler/resources:/app/resources
    command: java -jar /app/app.jar /app/mounted-folder
    depends_on:
      - hazelcast-server

  query-engine:
    build:
      context: ./QueryEngine
    container_name: query-engine
    networks:
      - hazelcast-network
    ports:
      - "8080:8080"
    environment:
      - HAZELCAST_CONFIG=/app/resources/query_engine_hazelcast.xml
    volumes:
      - ./QueryEngine/resources:/app/resources

    command: java -jar /app/app.jar /app/resources/words/words.txt /app/queries/resources/queries.txt
    depends_on:
      - hazelcast-server


  nginx-dispatcher:
    build:
      context: ./nginx
    container_name: nginx-dispatcher
    networks:
      - hazelcast-network
    ports:
      - "80:80"
    depends_on:
      - query-engine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  hazelcast-network:
    driver: bridge